# -*- coding: utf-8 -*-
"""RockPaperScissorsGame4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYwk1Xv9f9fWcD20_xaT3cAgBIxyLl-j
"""

# 🎮 Rock, Paper, Scissors Game

import random

print("🪨📄✂️ Welcome to Rock, Paper, Scissors Game!")
print("👉 Type your choice: 'rock', 'paper', or 'scissors'\n")

choices = ['rock', 'paper', 'scissors']
user_score = 0
computer_score = 0
rounds = 3  # Best of 3

for round_num in range(1, rounds + 1):
    print(f"\n🔁 Round {round_num}")
    user_choice = input("Your choice: ").lower()
    computer_choice = random.choice(choices)

    print(f"🤖 Computer chose: {computer_choice}")

    if user_choice == computer_choice:
        print("⚖️ It's a tie!")
    elif (user_choice == "rock" and computer_choice == "scissors") or \
         (user_choice == "paper" and computer_choice == "rock") or \
         (user_choice == "scissors" and computer_choice == "paper"):
        print("✅ You win this round!")
        user_score += 1
    elif user_choice in choices:
        print("❌ You lose this round!")
        computer_score += 1
    else:
        print("❗ Invalid input. No point awarded.")

# 🔚 Final Result
print("\n🏁 Game Over!")
print(f"🧑 Your score: {user_score} | 🤖 Computer score: {computer_score}")

if user_score > computer_score:
    print("🎉 Congratulations! You won the game.")
elif user_score < computer_score:
    print("😢 Oops! Computer won the game.")
else:
    print("🤝 It's a tie game.")

