# -*- coding: utf-8 -*-
"""MadslibProject1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OGm7phTO1wneVgdi9yYLnncc5DYkwwhi
"""

# 📝 Mad Libs Game - Google Colab Version

# 🎮 Introduction
print("🎉 Welcome to the Mad Libs Game!")
print("👉 Fill in the blanks to create a fun story.\n")

# 🧠 Taking Inputs
name = input("Enter a name: ")
place = input("Enter a place: ")
animal = input("Enter an animal: ")
food = input("Enter a type of food: ")
verb = input("Enter a verb ending in -ing: ")
emotion = input("Enter an emotion: ")
object_name = input("Enter an object: ")

# 📖 Creating the story
story = f"""
📖 Here is your Mad Libs Story:

Once upon a time in {place}, there lived a person named {name}.
One day, {name} saw a {animal} running with a {object_name} in its mouth.
Apparently, the {animal} had stolen someone's {food} and was now {verb} joyfully.
Watching this scene made {name} feel very {emotion}.
It was a day to remember in the streets of {place}!

🎉 The End.
"""

# 🖨️ Displaying the story
print(story)

