# -*- coding: utf-8 -*-
"""Password7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7lPhO3KlLcdSgdgHt5iPEENYzLXNKHJ
"""

# 🔐 Password Generator in Python

import random
import string

def generate_password(length):
    if length < 4:
        return "⚠️ Password length should be at least 4 characters!"

    # Characters to include
    letters = string.ascii_letters
    digits = string.digits
    symbols = string.punctuation

    # Ensure password has at least one of each
    password = [
        random.choice(letters),
        random.choice(digits),
        random.choice(symbols)
    ]

    # Fill the rest with random choices
    all_chars = letters + digits + symbols
    password += random.choices(all_chars, k=length - 3)

    # Shuffle it to avoid predictable pattern
    random.shuffle(password)

    return ''.join(password)

# 📥 User input
try:
    user_length = int(input("Enter desired password length: "))
    final_password = generate_password(user_length)
    print("\n🔐 Your Generated Password:", final_password)
except ValueError:
    print("⚠️ Please enter a valid number!")

