# -*- coding: utf-8 -*-
"""Hangman5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PxlqRLV8z5Fm1tvR5JFqvH0JeFfHsCgq
"""

# 🎮 Hangman Game in Python

import random

# 📚 Word list (you can add more!)
words = ['python', 'developer', 'hangman', 'challenge', 'program', 'project']
word = random.choice(words).lower()

# 📊 Game variables
guessed_letters = []
tries = 6
display_word = ['_'] * len(word)

print("🪓 Welcome to the HANGMAN Game!")
print("Guess the letters before the hangman is fully drawn!\n")

# 🌀 Game loop
while tries > 0 and '_' in display_word:
    print("Word: ", ' '.join(display_word))
    print(f"❤️ Lives left: {tries}")
    guess = input("Enter a letter: ").lower()

    if len(guess) != 1 or not guess.isalpha():
        print("⚠️ Please enter a single valid alphabet letter!\n")
        continue

    if guess in guessed_letters:
        print("🔁 You already guessed that letter!\n")
        continue

    guessed_letters.append(guess)

    if guess in word:
        print("✅ Good guess!\n")
        for i in range(len(word)):
            if word[i] == guess:
                display_word[i] = guess
    else:
        print("❌ Wrong guess!\n")
        tries -= 1

# 🏁 Game result
if '_' not in display_word:
    print(f"\n🎉 Congratulations! You guessed the word: {word}")
else:
    print(f"\n💀 Game Over! The word was: {word}")