# -*- coding: utf-8 -*-
"""Website9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfPKogZWcj2epe0xa0K2je4Fv619FZXx
"""


import streamlit as st

# Page setup
st.set_page_config(page_title="My Portfolio", page_icon="💼", layout="wide")

# Sidebar navigation
st.sidebar.title("📍 Navigate")
selection = st.sidebar.radio("Go to", ["🏠 Home", "👤 About Me", "📁 Projects", "📬 Contact"])

# 🏠 Home Section
if selection == "🏠 Home":
    st.title("👋 Hello, I'm Aamna Ansari")
    st.subheader("💻 Aspiring Developer | Python Enthusiast | Web Lover")
    st.image("https://media.giphy.com/media/qgQUggAC3Pfv687qPC/giphy.gif", width=500)

    st.write("""
    Welcome to my interactive portfolio built with **Python & Streamlit**.  
    I love building apps, solving problems, and learning new tech every day! 🚀  
    Scroll through the sections to know more about me!
    """)

# 👤 About Section
elif selection == "👤 About Me":
    st.title("👤 About Me")
    col1, col2 = st.columns(2)
    with col1:
        st.image("pic1.jpg", width=300)
    with col2:
        st.write("""
        Hey there! I'm Aamna Ansari, a passionate Python developer with a knack for building cool web apps 💡  
        🔸 Skilled in: Python, HTML/CSS, Streamlit, and a bit of JavaScript  
        🔸 Goal: Become a full-stack developer & build meaningful tech solutions 🌟
        """)

# 📁 Projects Section
elif selection == "📁 Projects":
    st.title("📁 My Projects")
    st.write("Here are some projects I’ve worked on:")

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("🔢 BMI Calculator")
        st.write("A simple web app that calculates your Body Mass Index using Streamlit.")
        st.button("View Code", key="bmi")

    with col2:
        st.subheader("🎮 Rock Paper Scissors Game")
        st.write("Classic rock-paper-scissors game built in Python.")
        st.button("View Code", key="rps")

# 📬 Contact Section
elif selection == "📬 Contact":
    st.title("📬 Contact Me")
    st.write("Let's connect! Fill the form below.")

    name = st.text_input("Your Name")
    email = st.text_input("Your Email")
    message = st.text_area("Your Message")

    if st.button("Send"):
        if name and email and message:
            st.success("✅ Message sent successfully!")
        else:
            st.error("❌ Please fill all fields.")

# Footer
st.markdown("---")
st.caption("💼 Built with ❤️ using Python & Streamlit | © 2025 Aamna Ansari")
