# -*- coding: utf-8 -*-
"""Usernumbeguessgame3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ri34VUW5T4OtmbZcpMEHmjpUG5L5CxXu
"""

# 🎮 Guess the Number Game (User Chooses, Computer Guesses)

print("🧠 Think of a number between 1 and 100, and I (the computer) will try to guess it!")
print("Just respond with:")
print("   🔼 'h' if my guess is too high")
print("   🔽 'l' if my guess is too low")
print("   ✅ 'c' if my guess is correct\n")

low = 1
high = 100
attempts = 0

while low <= high:
    guess = (low + high) // 2
    attempts += 1

    print(f"My guess is: {guess}")
    feedback = input("Is it too high (h), too low (l), or correct (c)? ").lower()

    if feedback == 'h':
        high = guess - 1
    elif feedback == 'l':
        low = guess + 1
    elif feedback == 'c':
        print(f"\n🎉 Yay! I guessed your number in {attempts} attempts.")
        break
    else:
        print("⚠️ Invalid input! Please enter only 'h', 'l', or 'c'.")

