# -*- coding: utf-8 -*-
"""BMI8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C0Rx1p6pO2we3pktJ6C-BdJq_AgjLD22
"""

import streamlit as st

# 🧮 BMI Calculation Function
def calculate_bmi(weight, height):
    if height == 0:
        return 0
    return weight / (height ** 2)

# 🌐 Streamlit App UI
st.set_page_config(page_title="BMI Calculator", page_icon="💪", layout="centered")

st.title("💪 BMI Calculator")
st.write("### Check your Body Mass Index")

# 📥 Input Fields
weight = st.number_input("Enter your weight (in kg)", min_value=1.0, step=0.5)
height_cm = st.number_input("Enter your height (in cm)", min_value=10.0, step=0.5)

# 📏 Convert height to meters
height_m = height_cm / 100

# 🧮 Calculate BMI on button click
if st.button("Calculate BMI"):
    bmi = calculate_bmi(weight, height_m)
    st.success(f"Your BMI is: **{bmi:.2f}**")

    # 📊 BMI Categories
    if bmi < 18.5:
        st.warning("You're underweight 🥺")
    elif 18.5 <= bmi < 24.9:
        st.info("You're healthy 😎")
    elif 25 <= bmi < 29.9:
        st.warning("You're overweight 😅")
    else:
        st.error("You're obese 🥵")

st.markdown("---")
st.caption("Made by Aamna with ❤️ using Python & Streamlit")