# -*- coding: utf-8 -*-
"""Numbergame(computer)2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tV_OWlvSRsiOjE93Ejy5bCYDCC1f2kph
"""

# 🎮 Guess the Number Game - Computer Chooses the Number

import random

print("🎯 Welcome to the 'Guess the Number' Game!")
print("👉 I'm thinking of a number between 1 and 100.")
print("Can you guess what it is?\n")

# 🧠 Computer selects a random number
number_to_guess = random.randint(1, 100)
attempts = 0

# 🎯 Game Loop
while True:
    try:
        guess = int(input("Enter your guess (1-100): "))
        attempts += 1

        if guess < 1 or guess > 100:
            print("⚠️ Please guess a number between 1 and 100!")
        elif guess < number_to_guess:
            print("🔻 Too low! Try again.")
        elif guess > number_to_guess:
            print("🔺 Too high! Try again.")
        else:
            print(f"🎉 Congratulations! You guessed the number {number_to_guess} correctly in {attempts} attempts.")
            break
    except ValueError:
        print("❌ Invalid input! Please enter a valid number.")

