# -*- coding: utf-8 -*-
"""Countdown6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1Jdm3UMrqATlK6c7AR9YJYSNABDxRjC
"""

# ⏳ Countdown Timer in Python

import time

def countdown_timer(seconds):
    while seconds:
        mins = seconds // 60
        secs = seconds % 60
        timer_display = f"{mins:02d}:{secs:02d}"
        print(f"⏰ Time Left: {timer_display}", end="\r")
        time.sleep(1)
        seconds -= 1

    print("\n⏲️ Time's up! 🎉")

# 🔽 Get time from user
try:
    total_time = int(input("Enter countdown time in seconds: "))
    print("\nStarting countdown...\n")
    countdown_timer(total_time)
except ValueError:
    print("⚠️ Please enter a valid number!")

